---
name: Test Action setup-autopkg

on:
  push:
    paths:
      - ".github/workflows/Test_Action_setup-autopkg.yaml"
      - ".github/actions/setup-autopkg/**"
  pull_request:
    paths:
      - ".github/workflows/Test_Action_setup-autopkg.yaml"
      - ".github/actions/setup-autopkg/**"

jobs:
  TestAction_setup-autopkg:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Test Action setup-autopkg
    steps:
      - uses: actions/checkout@v6

      - name: setup-autopkg local action
        uses: ./.github/actions/setup-autopkg

      - name: run recipe autopkg
        run: python autopkg/Code/autopkg run -vv Test-Recipes/AutopkgCore.test.recipe.yaml
